"""Prometheus exposition format, generated by hand (no client library needed)."""

from __future__ import annotations

from .checks import STATUS_ORDER


def _esc(v: str) -> str:
    return v.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def render(snapshot: dict) -> str:
    lines: list[str] = []

    def metric(name: str, kind: str, help_: str) -> None:
        lines.append(f"# HELP {name} {help_}")
        lines.append(f"# TYPE {name} {kind}")

    def sample(name: str, labels: dict[str, str], value) -> None:
        if value is None:
            return
        lab = ",".join(f'{k}="{_esc(str(v))}"' for k, v in labels.items())
        lines.append(f"{name}{{{lab}}} {value}")

    metric("monad_rpc_up", "gauge", "1 if the endpoint answered eth_blockNumber on the last probe")
    metric("monad_rpc_status", "gauge", "1 for the endpoint's current status label, 0 otherwise")
    metric("monad_rpc_latency_ms", "gauge", "eth_blockNumber round-trip latency in milliseconds")
    metric("monad_rpc_block_number", "gauge", "Head block reported by the endpoint")
    metric("monad_rpc_lag_blocks", "gauge", "Blocks behind the best head observed on the network")
    metric("monad_rpc_uptime_ratio", "gauge", "Share of successful probes in the history window")
    metric("monad_rpc_latency_p95_ms", "gauge", "95th percentile latency in the history window")
    metric("monad_rpc_consistent", "gauge", "1 if the endpoint agrees with the majority block hash, 0 on mismatch")
    metric("monad_rpc_method_supported", "gauge", "1 if the JSON-RPC method is served, 0 if not")

    for e in snapshot["endpoints"]:
        base = {"network": e["network"], "endpoint": e["endpoint"], "provider": e.get("provider", "")}
        sample("monad_rpc_up", base, 1 if e["block"] is not None else 0)
        for st in STATUS_ORDER:
            sample("monad_rpc_status", {**base, "status": st}, 1 if e["status"] == st else 0)
        sample("monad_rpc_latency_ms", base, e["latency_ms"])
        sample("monad_rpc_block_number", base, e["block"])
        sample("monad_rpc_lag_blocks", base, e["lag"])
        if e.get("uptime_pct") is not None:
            sample("monad_rpc_uptime_ratio", base, round(e["uptime_pct"] / 100.0, 4))
        sample("monad_rpc_latency_p95_ms", base, e.get("p95_ms"))
        if e.get("consistency") in ("ok", "mismatch"):
            sample("monad_rpc_consistent", base, 1 if e["consistency"] == "ok" else 0)
        for key, r in (e.get("methods") or {}).items():
            if r.get("supported") is not None:
                sample("monad_rpc_method_supported", {**base, "method": key}, 1 if r["supported"] else 0)

    metric("monad_network_best_block", "gauge", "Best head observed across all endpoints of the network")
    metric("monad_network_healthy_endpoints", "gauge", "Number of endpoints currently healthy")
    metric("monad_network_endpoints", "gauge", "Number of endpoints monitored")
    for n, s in snapshot["networks"].items():
        sample("monad_network_best_block", {"network": n}, s["best_block"])
        sample("monad_network_healthy_endpoints", {"network": n}, s["endpoints_healthy"])
        sample("monad_network_endpoints", {"network": n}, s["endpoints_total"])

    metric("monad_rpc_monitor_last_run_timestamp", "gauge", "Unix time of the last completed probe cycle")
    lines.append(f"monad_rpc_monitor_last_run_timestamp {snapshot['generated_at']}")
    return "\n".join(lines) + "\n"
